### ISSUE TITLE
Independent backend (No more Albius)

### ISSUE THREAD

**Issue by korewaChino** [FyraLabs/readymade#8]
We need a full independent backend preferably based on work done in distinst or something, a rewrite of it perhaps

```[tasklist]
### Tasks
- [ ] Refactor structure to be backend-independent?
- [x] Deprecate Albius?
- [x] Partitioning shenanigans
- [ ] Finally make use of `backhand` and unsquash at lightning speeds!
- [ ] Possible EROFS support?
- [ ] Possibly a DBus system service backend like that of Anaconda or distinst v2?
```

**Comment by korewaChino** [comment]
update: possible replacement? https://0pointer.net/blog/fitting-everything-together.html

**Comment by gallium-stanza** [comment]
> update: possible replacement? https://0pointer.net/blog/fitting-everything-together.html

That would be great!
